title: "Habila Adamou"
project:
  type: website
publish:
  output-dir: docs
  site-url: https://adahabila227.github.io/Habila
  method: gh-pages
website:
  navbar:
    left:
      - text: "Accueil"
        href: index.qmd
      - text: "Recherches"
        href: recherches.qmd
      - text: "Publications"
        href: publications.qmd
      - text: "Lectures"
        href: lectures.qmd
      - text: "Blog" 
        href: blog.qmd
      - text: "Data"
        href: data.qmd 
    right:
      - text: "Réseaux sociaux"
        menu:
          - text: "ResearchGate"
            href: https://www.researchgate.net/profile/Habila-Adamou
          - text: "ORCID"
            href: https://orcid.org/0000-0001-5833-4714
          - text: "Google Scholar"
            href: https://scholar.google.fr/citations?user=xbXaFOsAAAAJ
          - text: "LinkedIn"
            href: https://www.linkedin.com/in/habila-adamou-2a5156226/
          - text: "HAL"
            href: https://hal.science/user/index/
    toc: true
    toc-location: left
format:
  html:
    css: styles.css


