---
title: "Habila Adamou"
toc: true
---

Démographe et candidat en 4ième année au Ph.D à l'[ÉSAD](https://www.esad.ulaval.ca/).
Mes recherches portent sur la santé des populations et l'analyse de données.

------------------------------------------------------------------------

### Formation académique 
- **Ph.D en Aménagement du territoire et développement régional**  
  Université Laval (2021- présent)

- **Master en Démographie**  
  Institut de Formation et de Recherche Démographiques, Université de Yaoudé 2 (2018-2020)

- **Licence en Mathématiques**  
  Université Abdou Moumouni de Niamey (2014-2018)
  
### Expérience professionnelle
- **Chercheur - doctorant**  
  Plaforme d'évaluation en prévention de l'obésité ([PÉPO](https://evaluation-prevention-obesite.ulaval.ca/)) de l'institut universitaire de cardiologie et de pneumologie de Québec ([IUCPQ](https://www.iucpq.ca/)) (2021 - Présent)

- **Doctorant**  
  Centre de recherche en aménagement et développement ([CRAD](https://www.crad.ulaval.ca/)) (2021 - présent)
  
- **Assistant de recherche sur l'évaluation économique des impacts des CC**  
  École nationale d'administration publique de Québec ([ÉNAP](https://enap.ca/)) (Mai 2024 - présent)
  
- **Chargé de cours en Statistiques**  
  École nationale d'administration publique de Québec ([ÉNAP](https://enap.ca/)) (Septembre 2024 - présent)
  
- **Auxilliaire d'enseignement en analyse de données**  
  Université Laval ([UL](https://www.ulaval.ca/)) (Septembre 2023 - Décembre 2023)
  
- **Stagiaire en analyse de données**  
  Institut national de santé publique de Québec ([INSPQ](https://www.inspq.qc.ca/)) (mai 2022 - Mai 2024)
  
- **Stagiaire/analyste de données sociodémographiques**  
  Institut national de la statistque du Niger, direction régionale de Niamey ([INS](https://www.stat-niger.org/)) (Janvier 2020 - Juin 2020)

- **Responsable régional/Tillabéri**  
  Enquête nationale sur les violences basées sur le genre (15 mai 2020 - 15 Juin 2020) <br>
  
### Centres d’intérêt
- Santé des populations 
- Les déterminants sociaux de la santé
- Les enquêtes sociodémographiques
- Analyse de données 
- Modélisation statistique
- Une curiosité pour l'économie des changements climatiques <br>

### Réseaux sociaux
- [ResearchGate](https://www.researchgate.net/profile/Habila-Adamou)  
- [ORCID](https://orcid.org/0000-0001-5833-4714)
- [Google scholar](https://scholar.google.fr/citations?user=xbXaFOsAAAAJ)
- [Linkedin](https://www.linkedin.com/in/habila-adamou-2a5156226/)
- [HAL](https://hal.science/user/index/)

